import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from './components/Hero'

import {app,db, querySnapshot} from './services/firebase'

export default function Home() {

const onHandleClick = () => {
  console.log('App', app);
  console.log('DB', db);
  querySnapshot;
}

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <button onClick={onHandleClick}>Click</button>
    </div>
  )
}
